### ISSUE TITLE
Error in sentence segmentation

### ISSUE THREAD

**Issue by nhittt** [lngvietthang/das#6]
Sentences/paragraphs are in several lines.
For example: (in 8c4e17f5113efac11a8d1428594669495490d93a.story)

> @highlight
> 
> Both Krueger, 23, and Warner, 26, were
>  charged Tuesday with special circumstances murder and assault on a 
> child causing death 

And we have one highlight in list of highlights (preprocessing.py) 

> Both Krueger, 23, and Warner, 26, were

The same with sentence in content.

**Comment by lngvietthang** [comment]
I fixed it. @nhittt could you check it again? Thank!
